[[AbstractFFTs]]
deps = ["Compat", "LinearAlgebra"]
git-tree-sha1 = "8d59c3b1463b5e0ad05a3698167f85fac90e184d"
uuid = "621f4979-c628-5d54-868e-fcf4e3e8185c"
version = "0.3.2"

[[ApproxFun]]
deps = ["AbstractFFTs", "BandedMatrices", "BlockArrays", "BlockBandedMatrices", "Calculus", "DSP", "DomainSets", "DualNumbers", "FFTW", "FastGaussQuadrature", "FastTransforms", "FillArrays", "InfiniteArrays", "IntervalSets", "LazyArrays", "LinearAlgebra", "LowRankApprox", "Random", "RecipesBase", "SparseArrays", "SpecialFunctions", "StaticArrays", "Statistics", "Test", "ToeplitzMatrices"]
git-tree-sha1 = "726f18e66263266988788ef9d22227125c194ad8"
uuid = "28f2ccd6-bb30-5033-b560-165f7b14dc2f"
version = "0.10.0"

[[ArgParse]]
deps = ["Compat", "Test", "TextWrap"]
git-tree-sha1 = "14d5789a99e6bea3e258d668ec09359a9feaf2d1"
uuid = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
version = "0.6.2"

[[BPJSpec]]
deps = ["ApproxFun", "CasaCore", "Cosmology", "Cubature", "FastTransforms", "GSL", "JLD2", "MacroTools", "ProgressMeter", "StaticArrays", "Unitful", "UnitfulAstro"]
git-tree-sha1 = "a2c94c0b8285e75850fd77e34cd50a2714cef447"
repo-rev = "master"
repo-url = "https://github.com/ovro-lwa/BPJSpec.jl"
uuid = "c2f8ae53-54de-5277-a835-27bc461b6c12"
version = "0.0.0"

[[BandedMatrices]]
deps = ["FillArrays", "LazyArrays", "LinearAlgebra", "Random", "SparseArrays", "Test"]
git-tree-sha1 = "913325add4b83f380e5fb83df9e6cfad36025bc9"
uuid = "aae01518-5342-5314-be14-df237901396f"
version = "0.7.1"

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[BinDeps]]
deps = ["Compat", "Libdl", "SHA", "URIParser"]
git-tree-sha1 = "12093ca6cdd0ee547c39b1870e0c9c3f154d9ca9"
uuid = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
version = "0.8.10"

[[BinaryProvider]]
deps = ["Libdl", "Logging", "SHA"]
git-tree-sha1 = "ecdec412a9abc8db54c0efc5548c64dfce072058"
uuid = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
version = "0.5.10"

[[BlockArrays]]
deps = ["Base64", "LinearAlgebra", "SparseArrays", "Test"]
git-tree-sha1 = "68a477c2f2ddbbe518dc31a42aaf2df38bdfd93c"
uuid = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
version = "0.7.0"

[[BlockBandedMatrices]]
deps = ["BandedMatrices", "BlockArrays", "Distributed", "FillArrays", "LazyArrays", "LinearAlgebra", "Pkg", "Profile", "SharedArrays", "SparseArrays", "Statistics", "Test"]
git-tree-sha1 = "b3919df677a370cdd1975484c078938e680a82f9"
uuid = "ffab5731-97b5-5995-9138-79e8c1846df0"
version = "0.2.0"

[[CMake]]
deps = ["BinDeps"]
git-tree-sha1 = "50a8b41d2c562fccd9ab841085fc7d1e2706da82"
uuid = "631607c0-34d2-5d66-819e-eb0f9aa2061a"
version = "1.2.0"

[[CMakeWrapper]]
deps = ["BinDeps", "CMake", "Libdl", "Parameters", "Test"]
git-tree-sha1 = "cd82e6082a144e2425bcba6e5fdf5b404401c8e4"
uuid = "d5fb7624-851a-54ee-a528-d3f3bac0b4a0"
version = "0.2.4"

[[Calculus]]
deps = ["Compat"]
git-tree-sha1 = "f60954495a7afcee4136f78d1d60350abd37a409"
uuid = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
version = "0.4.1"

[[CasaCore]]
deps = ["StaticArrays", "Unitful"]
git-tree-sha1 = "43e17ed4cae4978e670313c4789dc17e12792bc1"
repo-rev = "master"
repo-url = "https://github.com/ovro-lwa/CasaCore.jl"
uuid = "f971ce14-3f7e-543c-a8de-37d93de32579"
version = "0.0.0"

[[CodecZlib]]
deps = ["BinaryProvider", "Libdl", "Test", "TranscodingStreams"]
git-tree-sha1 = "36bbf5374c661054d41410dc53ff752972583b9b"
uuid = "944b1d66-785c-5afd-91f1-9de20f533193"
version = "0.5.2"

[[Codecs]]
deps = ["Test"]
git-tree-sha1 = "70885e5e038cba1c4c17a84ad6c40756e10a4fb5"
uuid = "19ecbf4d-ef7c-5e4b-b54a-0a0ff23c5aed"
version = "0.5.0"

[[Compat]]
deps = ["Base64", "Dates", "DelimitedFiles", "Distributed", "InteractiveUtils", "LibGit2", "Libdl", "LinearAlgebra", "Markdown", "Mmap", "Pkg", "Printf", "REPL", "Random", "Serialization", "SharedArrays", "Sockets", "SparseArrays", "Statistics", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "b0b7e8a0d054fada22b64095b46469627a138943"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "2.2.1"

[[Conda]]
deps = ["JSON", "VersionParsing"]
git-tree-sha1 = "9a11d428dcdc425072af4aea19ab1e8c3e01c032"
uuid = "8f4d0f93-b110-5947-807f-2305c1781a2d"
version = "1.3.0"

[[Cosmology]]
deps = ["QuadGK", "Test", "Unitful", "UnitfulAstro"]
git-tree-sha1 = "38a7995285fcff298532cd013199b1426d72af2c"
uuid = "76746363-e552-5dba-9a5a-cef6fa9cc5ab"
version = "0.5.0"

[[Cubature]]
deps = ["BinDeps", "Libdl", "Test"]
git-tree-sha1 = "f6db932217f0d12ca91279265929b35e2c203c83"
uuid = "667455a9-e2ce-5579-9412-b964f529a492"
version = "1.3.1"

[[DSP]]
deps = ["AbstractFFTs", "Compat", "FFTW", "LinearAlgebra", "Polynomials", "Random", "Reexport", "SpecialFunctions"]
git-tree-sha1 = "5ec38ebc4ddf6320ad50b826eb8fd7fb521993a5"
uuid = "717857b8-e6f2-59f4-9121-6e50c889abd2"
version = "0.5.2"

[[DataStructures]]
deps = ["InteractiveUtils", "OrderedCollections", "Random", "Serialization", "Test"]
git-tree-sha1 = "e5bf54defdcdbd51e5a61fe0fe2ee9a7d428b36c"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.16.1"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DelimitedFiles]]
deps = ["Mmap"]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[Dierckx]]
deps = ["BinaryProvider", "Libdl", "Random", "Test"]
git-tree-sha1 = "27a74763c20938a814da26f31a9e8408d16fec44"
uuid = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
version = "0.4.1"

[[Distributed]]
deps = ["LinearAlgebra", "Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[DocOpt]]
deps = ["Dates", "Printf"]
git-tree-sha1 = "866efe767d646ee8c66b15ff22520c03a1200ca7"
uuid = "968ba79b-81e4-546f-ab3a-2eecfa62a9db"
version = "0.4.2"

[[DomainSets]]
deps = ["IntervalSets", "LinearAlgebra", "StaticArrays", "Statistics", "Test"]
git-tree-sha1 = "84beb94a9595c1a7a692880b424f82470a326976"
uuid = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
version = "0.0.1"

[[DualNumbers]]
deps = ["Calculus", "LinearAlgebra", "NaNMath", "SpecialFunctions", "Test"]
git-tree-sha1 = "e178a6768dad879ff1abfc1c612406856bb06ce0"
uuid = "fa6b7ba4-c1ee-5f82-b5fc-ecf0adba8f74"
version = "0.6.2"

[[FFTW]]
deps = ["AbstractFFTs", "BinaryProvider", "Compat", "Conda", "Libdl", "LinearAlgebra", "Reexport", "Test"]
git-tree-sha1 = "29cda58afbf62f35b1a094882ad6c745a47b2eaa"
uuid = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
version = "0.2.4"

[[FastGaussQuadrature]]
deps = ["Compat", "LinearAlgebra", "SpecialFunctions"]
git-tree-sha1 = "769ac4057ed875f433372e9a571a2cb86347d1be"
uuid = "442a2c76-b920-505d-bb47-c5924d526838"
version = "0.3.3"

[[FastTransforms]]
deps = ["AbstractFFTs", "Compat", "DSP", "FFTW", "HierarchicalMatrices", "LinearAlgebra", "LowRankApprox", "ProgressMeter", "SpecialFunctions", "ToeplitzMatrices"]
git-tree-sha1 = "f7f912b0f00cdf5b4632c840aa7954be0de4b965"
uuid = "057dd010-8810-581a-b7be-e3fc3b93f78c"
version = "0.5.0"

[[FileIO]]
deps = ["Pkg", "Requires", "UUIDs"]
git-tree-sha1 = "9267e5f50b0e12fdfd5a2455534345c4cf2c7f7a"
uuid = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
version = "1.14.0"

[[FillArrays]]
deps = ["LinearAlgebra", "Random", "SparseArrays", "Test"]
git-tree-sha1 = "2def0123a4f3572234405b0e3d80bfe5d3e1a2a4"
uuid = "1a297f60-69ca-5386-bcde-b61e274b549b"
version = "0.5.0"

[[GSL]]
deps = ["BinaryProvider", "Compat", "Libdl", "Test"]
git-tree-sha1 = "b001d22c3d3efb302f74ee6b946a19f8e59a86c1"
uuid = "92c85e6c-cbff-5e0c-80f7-495c94daaecd"
version = "0.4.0"

[[HierarchicalMatrices]]
deps = ["Compat"]
git-tree-sha1 = "acfcaf1aa47d038f593f301ed3bdebc0129035bc"
uuid = "7c893195-952b-5c83-bb6e-be12f22eed51"
version = "0.1.4"

[[InfiniteArrays]]
deps = ["DSP", "FillArrays", "LazyArrays", "LinearAlgebra", "SparseArrays", "Statistics", "Test"]
git-tree-sha1 = "e65228707f83519678abeb780ff0d53cebcc2584"
uuid = "4858937d-0d70-526a-a4dd-2d5cb5dd786c"
version = "0.0.2"

[[InteractiveUtils]]
deps = ["LinearAlgebra", "Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[IntervalSets]]
deps = ["Dates", "Statistics"]
git-tree-sha1 = "4214b48a62eb8f2c292b2ee34a508c256c0cdbc9"
uuid = "8197267c-284f-5f27-9208-e0e47529a953"
version = "0.3.2"

[[JLD2]]
deps = ["CodecZlib", "DataStructures", "FileIO", "Mmap", "Printf"]
git-tree-sha1 = "343d1ec8ae7d57a608d79ef12e9a853cbb9acd96"
uuid = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
version = "0.1.3"

[[JSON]]
deps = ["Dates", "Mmap", "Parsers", "Unicode"]
git-tree-sha1 = "81690084b6198a2e1da36fcfda16eeca9f9f24e4"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.21.1"

[[LazyArrays]]
deps = ["FillArrays", "LinearAlgebra", "StaticArrays", "Test"]
git-tree-sha1 = "7b15209c5de4b06a67ad601086b93acbe786683a"
uuid = "5078a376-72f3-5289-bfd5-ec5146d43c02"
version = "0.3.2"

[[LibGit2]]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[LowRankApprox]]
deps = ["FFTW", "FillArrays", "LinearAlgebra", "Nullables", "Random", "SparseArrays", "Test"]
git-tree-sha1 = "4079dfefba2cf541e0770e6426f7756ee90efbe8"
uuid = "898213cb-b102-5a47-900c-97e73b919f73"
version = "0.2.3"

[[MacroTools]]
deps = ["Compat"]
git-tree-sha1 = "3fd1a3022952128935b449c33552eb65895380c1"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.4.5"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[MathProgBase]]
deps = ["Compat"]
git-tree-sha1 = "3bf2e534e635df810e5f4b4f1a8b6de9004a0d53"
uuid = "fdba3010-5040-5b88-9595-932c9decdf73"
version = "0.7.7"

[[Missings]]
deps = ["Dates", "InteractiveUtils", "SparseArrays", "Test"]
git-tree-sha1 = "d1d2585677f2bd93a97cfeb8faa7a0de0f982042"
uuid = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
version = "0.4.0"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[NLopt]]
deps = ["BinaryProvider", "CMakeWrapper", "Libdl", "MathProgBase", "Test"]
git-tree-sha1 = "b46237debcacd4fed7bbeb31200667a75b90384f"
uuid = "76087f3c-5699-56af-9a33-bf431cd00edd"
version = "0.5.1"

[[NaNMath]]
deps = ["Compat"]
git-tree-sha1 = "ce3b85e484a5d4c71dd5316215069311135fa9f2"
uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
version = "0.3.2"

[[Nullables]]
git-tree-sha1 = "8f87854cc8f3685a60689d8edecaa29d2251979b"
uuid = "4d1e1d77-625e-5b40-9113-a560ec7a8ecd"
version = "1.0.0"

[[OrderedCollections]]
git-tree-sha1 = "85f8e6578bf1f9ee0d11e7bb1b1456435479d47c"
uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
version = "1.4.1"

[[Parameters]]
deps = ["Markdown", "OrderedCollections", "REPL", "Test"]
git-tree-sha1 = "70bdbfb2bceabb15345c0b54be4544813b3444e4"
uuid = "d96e819e-fc66-5662-9728-84c9c7592b0a"
version = "0.10.3"

[[Parsers]]
deps = ["Dates", "Mmap", "Test"]
git-tree-sha1 = "127ff1b0b8593f8b73a178e5615d1a2a9d94ccf4"
uuid = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
version = "0.3.0"

[[Pkg]]
deps = ["Dates", "LibGit2", "Markdown", "Printf", "REPL", "Random", "SHA", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Polynomials]]
deps = ["LinearAlgebra", "RecipesBase"]
git-tree-sha1 = "f7c0c07e82798aef542d60a6e6e85e39f4590750"
uuid = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
version = "0.5.3"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[Profile]]
deps = ["Printf"]
uuid = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"

[[ProgressMeter]]
deps = ["Distributed", "Printf"]
git-tree-sha1 = "d7a7aef8f8f2d537104f170139553b14dfe39fe9"
uuid = "92933f4c-e287-5a05-a399-4b506db050ca"
version = "1.7.2"

[[QuadGK]]
deps = ["DataStructures", "LinearAlgebra"]
git-tree-sha1 = "78aadffb3efd2155af139781b8a8df1ef279ea39"
uuid = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
version = "2.4.2"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[RecipesBase]]
deps = ["Random", "Test"]
git-tree-sha1 = "b18c3d875ad6805e3db59c4e81f206f04df71d66"
uuid = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
version = "0.5.0"

[[Reexport]]
deps = ["Pkg"]
git-tree-sha1 = "7b1d07f411bc8ddb7977ec7f377b97b158514fe0"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "0.2.0"

[[Requires]]
deps = ["UUIDs"]
git-tree-sha1 = "838a3a4188e2ded87a4f9f184b4b0d78a1e91cb7"
uuid = "ae029012-a4dd-5104-9daa-d747884805df"
version = "1.3.0"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SharedArrays]]
deps = ["Distributed", "Mmap", "Random", "Serialization"]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SortingAlgorithms]]
deps = ["DataStructures", "Random", "Test"]
git-tree-sha1 = "03f5898c9959f8115e30bc7226ada7d0df554ddd"
uuid = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
version = "0.3.1"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[SpecialFunctions]]
deps = ["BinDeps", "BinaryProvider", "Libdl", "Test"]
git-tree-sha1 = "0b45dc2e45ed77f445617b99ff2adf0f5b0f23ea"
uuid = "276daf66-3868-5448-9aa4-cd146d93841b"
version = "0.7.2"

[[StaticArrays]]
deps = ["InteractiveUtils", "LinearAlgebra", "Random", "Statistics", "Test"]
git-tree-sha1 = "3841b39ed5f047db1162627bf5f80a9cd3e39ae2"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
version = "0.10.3"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[StatsBase]]
deps = ["DataStructures", "DelimitedFiles", "LinearAlgebra", "Missings", "Printf", "Random", "SortingAlgorithms", "SparseArrays", "Statistics", "Test"]
git-tree-sha1 = "435707791dc85a67d98d671c1c3fcf1b20b00f94"
uuid = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
version = "0.29.0"

[[TTCal]]
deps = ["CasaCore", "FileIO", "JLD2", "JSON", "NLopt", "ProgressMeter", "StaticArrays", "Unitful", "UnitfulAstro"]
git-tree-sha1 = "3d706fed65d0cfcee47823dfbad40b5fb99f0fab"
repo-rev = "trunk"
repo-url = "https://github.com/ovro-lwa/TTCal.jl"
uuid = "48f8b5cb-992a-5e5c-a443-c4363f5645c9"
version = "0.0.0"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[TextWrap]]
deps = ["Compat", "Test"]
git-tree-sha1 = "8355cc559e85469cd4dbe927c375f61d3750e002"
uuid = "b718987f-49a8-5099-9789-dcd902bef87d"
version = "0.3.0"

[[ToeplitzMatrices]]
deps = ["Compat", "FFTW", "LinearAlgebra", "StatsBase"]
git-tree-sha1 = "5242fdbeafe1f2e0187935bb13a5c651d5626106"
uuid = "c751599d-da0a-543b-9d20-d0a503d91d24"
version = "0.5.0"

[[TranscodingStreams]]
deps = ["Pkg", "Random", "Test"]
git-tree-sha1 = "a34a2d588e2d2825602bf14a24216d5c8b0921ec"
uuid = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
version = "0.8.1"

[[URIParser]]
deps = ["Unicode"]
git-tree-sha1 = "53a9f49546b8d2dd2e688d216421d050c9a31d0d"
uuid = "30578b45-9adc-5946-b283-645ec420af67"
version = "0.4.1"

[[UUIDs]]
deps = ["Random"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[Unitful]]
deps = ["LinearAlgebra", "Random", "Test"]
git-tree-sha1 = "cef7da6d4e9735fae7c11cd28e77b76fd87db468"
uuid = "1986cc42-f94f-5a68-af5c-568840ba703d"
version = "0.12.0"

[[UnitfulAngles]]
deps = ["Dates", "Test", "Unitful"]
git-tree-sha1 = "76b2596b39ebc4efd1ad2430872e4a369155b453"
uuid = "6fb2a4bd-7999-5318-a3b2-8ad61056cd98"
version = "0.2.0"

[[UnitfulAstro]]
deps = ["Test", "Unitful", "UnitfulAngles"]
git-tree-sha1 = "c786871755778ea9520c7cbb967f80dbb40d4d6f"
uuid = "6112ee07-acf9-5e0f-b108-d242c714bf9f"
version = "0.2.0"

[[VersionParsing]]
git-tree-sha1 = "58d6e80b4ee071f5efd07fda82cb9fbe17200868"
uuid = "81def892-9a0e-5fdd-b105-ffc91e053289"
version = "1.3.0"

[[YAML]]
deps = ["Codecs", "Compat"]
git-tree-sha1 = "3bde77cee95cce0c0b9b18813d85e18e8ed4f415"
uuid = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
version = "0.3.2"
